CREATE TABLE IF NOT EXISTS billboard_cover(
id BIGINT auto_increment PRIMARY KEY NOT NULL,
title VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
link VARCHAR(70) NOT NULL,
image_url VARCHAR(70) NOT NULL,
tag VARCHAR(70) NOT NULL,
added_at DATE DEFAULT CURRENT_DATE,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);