create table if not exists products(
id BIGINT auto_increment PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
description VARCHAR(500),
links VARCHAR(255) NOT NULL,
price DECIMAL(10, 2) NOT NULL,
rating DECIMAL(2,1) NOT NULL DEFAULT 0.0,
from_country VARCHAR(50) NOT NULL DEFAULT "Argentina",
material VARCHAR(100),
discount DECIMAL(5, 2) NOT NULL DEFAULT 0,
special_offer TINYINT(1) NOT NULL DEFAULT 0,
tags VARCHAR(255) NOT NULL,
categories VARCHAR(255) NOT NULL,
image_url VARCHAR(500) NOT NULL,
in_catalogue TINYINT(1) NOT NULL DEFAULT 1,
added_at DATE NOT NULL DEFAULT CURRENT_DATE,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);